spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:5432/${POSTGRES_DB:fintech}
    username: ${POSTGRES_USER:fintech}
    password: ${POSTGRES_PASSWORD:fintech}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

fintech:
  disbursement:
    banking:
      # En Docker los servicios se hablan por nombre y puerto interno.
      base-url: ${BANKING_BASE_URL:http://banking-service:8080}

logging:
  level:
    com.fintech: INFO
