spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:5432/${POSTGRES_DB:fintech}
    username: ${POSTGRES_USER:fintech}
    password: ${POSTGRES_PASSWORD:fintech}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

logging:
  level:
    com.fintech: INFO
